name: NARS Lab
description: Network science and machine learning for accessible, resilient and sustainable communities.
url: https://narslab.org

#markdown: redcarpet
permalink: /:categories/:title/
future: true

plugins:
  - jekyll-twitter-plugin
  - jekyll-include-cache

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/covid-analysis/results/*"
  - "projects/covid-analysis/NYT*"
  - "projects/covid-analysis/mobility/*"
  - "projects/covid-analysis/rscripts/*"
  - "projects/covid-analysis/.ipynb_checkpoints/*"
  - "projects/covid-analysis/da*"
  - "projects/covid-analysis/c*"
  - "projects/covid-analysis/9*"
  - "projects/nextflu/auspice/zika/*"
  - "projects/nextflu/auspice/zibra/*"
  - "projects/nextflu/auspice/muttree/*"
  - "projects/nextflu/auspice/reports/*"
  - "projects/nextflu/auspice/js/*"
  - "projects/nextflu/auspice/cdc/*"
  - "projects/nextflu/auspice/gisaid/*"
  - "projects/auspice/src/*"
  - "projects/siv-cst/beast/main/empiricalTrees/xml/*"
  - "projects/siv-cst/beast/supplement/discreteTraits/xml/*"
  - "projects/siv-cst/beast/supplement/empiricalTrees/xml/*"
  - "projects/h3n2-reassortment/auspice/*"
  - "projects/dengue-antigenic-dynamics/titer_model/seasia_output/*"
  - "projects/h5n1-cambodia/data/tree-jsons/*"
  - "projects/zika-colombia/supplemental-analysis/rarefaction-curves/*"
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
projects:
  - narslab/covid-analysis



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
